module.exports={
    USER_COLLECTIONS:'user',
    PRODUCT_COLLECTIONS:'PRODUCT',
    CATEGORY_COLLECTIONS:'category',
    SUBCATEGORY_COLLECTIONS:'SubCategory',
    CART_COLLECTIONS:'Cart',
    ORDER_COLLECTIONS:'Order'
    
}